services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    entrypoint: ./utils/app-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:14.3-alpine3.16
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.0.1-alpine3.16
volumes:
  db:
    driver: local